FROM python:3.10.7

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update
RUN apt install -y cron

RUN apt install -y joe 
RUN apt install -y redis
RUN apt install -y nginx
RUN apt install -y postgresql-client

# COPY src/base3src /app/base3src
# COPY src/tshared_src /app/tshared_src
# COPY src/requirements.txt /app/
# COPY src/requirements.sh /app/
COPY src/   /app

RUN pip install --upgrade pip
RUN pip install wheel
RUN /app/requirements.sh

ENV PYTHONPATH /app

