FROM python:3.10.7

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update
RUN apt install -y cron

RUN apt install -y joe vim redis nginx postgresql-client poppler-utils

COPY src/   /app

RUN pip install --upgrade pip && pip install wheel && /app/requirements.sh

ENV PYTHONPATH /app

