services:

  nginx:
#    image: nginx
    build:
      context: .
      dockerfile: docker-files/nginx/Dockerfile

#    volumes:
#      - ./docker-files/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - './src:/app'

    ports:
      - 8080:80

#    depends_on:
#      - v3

    environment:
      - NGINX_PORT=80
    extra_hosts:
      - "host.docker.internal:host-gateway"


  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server
    labels:
      NAME: redis
      

#  v3_workers:
#    build:
#      context: v3/.
#      dockerfile: Dockerfile.v3_workers
#
#    env_file:
#      - installation.env
#      - v3/src/environments/.env.docker
#      - credetials.env
#
#    command:  sleep 99999 #/app/start_workers.sh
#
#    volumes:
#      - type: bind
#        source: v3.txt
#        target: /tmp/v3.txt
#
#
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  base:
    build:
      context: .
      dockerfile: src/svc_base/Dockerfile
    command: python3 /app/monolith_service_args.py --port 7011 --service base

    volumes:
      - './src:/app'
      - '/var/log/impresa/v3_services:/app/logs'

    extra_hosts:
      - "host.docker.internal:host-gateway"

  
