FROM python:3.10.4

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update
RUN apt install -y cron

RUN apt install -y joe 
RUN apt install -y redis
RUN apt install -y postgresql-client

COPY base3src /app/base3src
COPY tshared_src /app/tshared_src
COPY requirements.txt /app/
COPY requirements.sh /app/

RUN pip install --upgrade pip
RUN pip install wheel
RUN /app/requirements.sh

ENV PYTHONPATH /app
